apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-dev-consumer-analytics  
spec:
  template:
    spec:
      containers:
        - name: shopping-dev-consumer-analytics
          image: registry.example.com/shopping-dev-consumer-analytics/consumer-analytics@sha256:REPLACEME