apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-dev-consumer-analytics
  namespace: shopping-dev-consumer-analytics
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shopping-dev-consumer-analytics
  template:
    metadata:
      labels:
        app: shopping-dev-consumer-analytics
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"  
    spec:
      containers:
      - name: shopping-dev-consumer-analytics
        image: registry.example.com/shopping-dev-consumer-analytics/consumer-analytics:v1
        envFrom:
        - configMapRef:
            name: shopping-dev-consumer-analytics-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"