apiVersion: v1
kind: Service
metadata:
  name: shopping-dev-frontend-service
  namespace: shopping-dev-frontend
spec:
  selector:
    app: shopping-dev-frontend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP