apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-dev-websocket-config
data:
  # 서버 설정
  HOST: "0.0.0.0"
  PORT: "8001"
  
  # Redis
  REDIS_URL: "redis://:wjdqudwo@redis-master.redis.svc.cluster.local:6379/0"
  
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
  KAFKA_USER: "user1"
  KAFKA_PASSWORD: "wjdqudwo"
  KAFKA_SASL_MECHANISM: "PLAIN"
  
  # CORS 설정
  CORS_ORIGINS: "http://shopping-dev-frontend-service.shopping-dev-frontend.svc.cluster.local"
  
  # 로그 설정
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
