apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-dev-websocket
spec:
  template:
    spec:
      containers:
        - name: shopping-dev-websocket
          image: registry.example.com/shopping-dev-websocket/websocket@sha256:fde09475eca65c446b38bfa713aba4116647bfe1c19b77d55aa9ce9309890654
