apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopping-dev-websocket
resources:
  - ../../base
images:
  - name: registry.example.com/shopping-dev-websocket/websocket
    digest: sha256:e4c93e35d9c56c966b7cd3cce92e8e87456d92d518c974baaa4613276e22be0f
    newName: registry.example.com/shopping-dev-websocket/websocket
